build:
  maxIssues: 0

config:
  validation: true

complexity:
  LongMethod:
    active: true
    threshold: 80
    ignoreAnnotated:
      - Composable
  LongParameterList:
    active: true
    functionThreshold: 8
    constructorThreshold: 10
    ignoreAnnotated:
      - Composable

naming:
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - Composable
  MatchingDeclarationName:
    active: false

style:
  MagicNumber:
    active: false
  WildcardImport:
    active: true
  MaxLineLength:
    active: true
    maxLineLength: 140

formatting:
  active: true
  Indentation:
    active: false
  MaximumLineLength:
    maxLineLength: 140
