build:
  maxIssues: 0

config:
  validation: true

complexity:
  LongMethod:
    active: true
    threshold: 80
  LongParameterList:
    active: true
    functionThreshold: 8
    constructorThreshold: 10

style:
  MagicNumber:
    active: false
  WildcardImport:
    active: true
  MaxLineLength:
    active: true
    maxLineLength: 140

formatting:
  active: true
  MaximumLineLength:
    maxLineLength: 140
